formatter: "markdown table"

header-from: main.tf

sections:
  show:
    - inputs
    - outputs

sort:
  enabled: true
  by: name

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

settings:
  indent: 2
  read-comments: true
