// input.js — Keyboard input handler
// Exports: initInput(), isKeyHeld(key)

const heldKeys = new Set();

/**
 * Attaches keydown/keyup listeners to window.
 * Tracks physically-held keys; key-repeat events are ignored (held state is
 * stable for the full duration a key is physically held).
 */
export function initInput() {
  window.addEventListener('keydown', (e) => {
    // e.repeat is true for key-repeat events generated by the OS while a key
    // is held. We ignore those so the Set is only mutated on the actual
    // physical press / release, preventing any flicker.
    if (!e.repeat) {
      heldKeys.add(e.key);
    }
  });

  window.addEventListener('keyup', (e) => {
    heldKeys.delete(e.key);
  });
}

/**
 * Returns true if the given KeyboardEvent.key is currently held down.
 * @param {string} key - e.g. 'ArrowLeft', ' ', 'a'
 * @returns {boolean}
 */
export function isKeyHeld(key) {
  return heldKeys.has(key);
}
